In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

13:04:.0

In [44]:
data_path = "../data/BOLT Data Set.xlsx"
og_df = pd.read_excel(data_path)
og_df.head()

,Card Identifier,Transaction Date,Transaction Time,Risk Assessment,Payment Method,Transaction Value,Merchant Location,Card Present Status,Chip Usage,Cross-border Transaction (Yes/No),Acquiring Institution ID,Merchant Identifier,Merchant Category Code (MCC),Fraud Indicator (Yes/No)
0,card 1,2023-05-11,16:22:14.0,362.0,Paypass - Contactless,13.98,USA,CP,Yes,No,acquirer 1,merchant 1,5812.0,No
1,card 2,2023-06-05,15:16:35.0,602.0,Online,24.64,USA,CNP,No,No,acquirer 2,merchant 2,4121.0,No
2,card 3,2023-06-05,11:57:40.0,482.0,Unknown,15.00,USA,CNP,No,No,acquirer 3,merchant 3,7211.0,No
3,card 4,2023-07-20,18:26:30.0,947.0,Online,30.56,USA,CNP,No,No,acquirer 1,merchant 4,5814.0,No
4,card 5,2023-03-03,19:03:11.0,1382.0,Magnetic Stripe,50.85,USA,CP,No,No,acquirer 4,merchant 1,5812.0,No

In [46]:
clean_df = og_df.copy()

In [59]:
fraud_yes = clean_df[clean_df["fraud_indicator"] == "Yes"]

In [47]:
clean_df['Transaction Time'] = pd.to_datetime(clean_df['Transaction Time'], format='%H:%M:%S.%f', errors='coerce').dt.time

In [62]:
clean_df['transaction_time'].isna().sum()

22462

In [61]:
fraud_yes['transaction_time'].isna().sum()

80

In [50]:
clean_df.head()

,Card Identifier,Transaction Date,Transaction Time,Risk Assessment,Payment Method,Transaction Value,Merchant Location,Card Present Status,Chip Usage,Cross-border Transaction (Yes/No),Acquiring Institution ID,Merchant Identifier,Merchant Category Code (MCC),Fraud Indicator (Yes/No)
0,card 1,2023-05-11,16:22:14,362.0,Paypass - Contactless,13.98,USA,CP,Yes,No,acquirer 1,merchant 1,5812.0,No
1,card 2,2023-06-05,15:16:35,602.0,Online,24.64,USA,CNP,No,No,acquirer 2,merchant 2,4121.0,No
2,card 3,2023-06-05,11:57:40,482.0,Unknown,15.00,USA,CNP,No,No,acquirer 3,merchant 3,7211.0,No
3,card 4,2023-07-20,18:26:30,947.0,Online,30.56,USA,CNP,No,No,acquirer 1,merchant 4,5814.0,No
4,card 5,2023-03-03,19:03:11,1382.0,Magnetic Stripe,50.85,USA,CP,No,No,acquirer 4,merchant 1,5812.0,No

In [52]:
list(og_df.columns)

['Card Identifier',
 'Transaction Date',
 'Transaction Time',
 'Risk Assessment',
 'Payment Method',
 'Transaction Value',
 'Merchant Location',
 'Card Present Status',
 'Chip Usage',
 'Cross-border Transaction (Yes/No)',
 'Acquiring Institution ID',
 'Merchant Identifier',
 'Merchant Category Code (MCC)',
 'Fraud Indicator (Yes/No)']

In [55]:
new_column_names = ['card_id',
 'transaction_date',
 'transaction_time',
 'risk_assessment',
 'payment_method',
 'transaction_value',
 'merchant_location',
 'card_present_status',
 'chip_usage',
 'cross_border_transaction',
 'acquirer_id',
 'merchant_id',
 'merchant_category_code',
 'fraud_indicator']

In [56]:
clean_df.columns = new_column_names

In [57]:
clean_df.head()

,card_id,transaction_date,transaction_time,risk_assessment,payment_method,transaction_value,merchant_location,card_present_status,chip_usage,cross_border_transaction,acquirer_id,merchant_id,merchant_category_code,fraud_indicator
0,card 1,2023-05-11,16:22:14,362.0,Paypass - Contactless,13.98,USA,CP,Yes,No,acquirer 1,merchant 1,5812.0,No
1,card 2,2023-06-05,15:16:35,602.0,Online,24.64,USA,CNP,No,No,acquirer 2,merchant 2,4121.0,No
2,card 3,2023-06-05,11:57:40,482.0,Unknown,15.00,USA,CNP,No,No,acquirer 3,merchant 3,7211.0,No
3,card 4,2023-07-20,18:26:30,947.0,Online,30.56,USA,CNP,No,No,acquirer 1,merchant 4,5814.0,No
4,card 5,2023-03-03,19:03:11,1382.0,Magnetic Stripe,50.85,USA,CP,No,No,acquirer 4,merchant 1,5812.0,No

In [58]:
clean_df.to_csv("../data/data_time_cleaned.csv", index=False)

In [64]:
clean_df.to_excel('../data/data_time_cleaned.xlsx', index=False)

In [41]:
df.head()

,Card Identifier,Transaction Date,Transaction Time,Risk Assessment,Payment Method,Transaction Value,Merchant Location,Card Present Status,Chip Usage,Cross-border Transaction (Yes/No),Acquiring Institution ID,Merchant Identifier,Merchant Category Code (MCC),Fraud Indicator (Yes/No)
0,1,2023-05-11,1900-01-01 16:22:14,362.0,Paypass - Contactless,13.98,USA,CP,Yes,No,acquirer 1,merchant 1,5812.0,No
1,2,2023-06-05,1900-01-01 15:16:35,602.0,Online,24.64,USA,CNP,No,No,acquirer 2,merchant 2,4121.0,No
2,3,2023-06-05,1900-01-01 11:57:40,482.0,Unknown,15.00,USA,CNP,No,No,acquirer 3,merchant 3,7211.0,No
3,4,2023-07-20,1900-01-01 18:26:30,947.0,Online,30.56,USA,CNP,No,No,acquirer 1,merchant 4,5814.0,No
4,5,2023-03-03,1900-01-01 19:03:11,1382.0,Magnetic Stripe,50.85,USA,CP,No,No,acquirer 4,merchant 1,5812.0,No

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 14 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Card Identifier                    100000 non-null  object
 1   Transaction Date                   100000 non-null  datetime64[ns]
 2   Transaction Time                   100000 non-null  object
 3   Risk Assessment                    99028 non-null   float64
 4   Payment Method                     100000 non-null  object
 5   Transaction Value                  100000 non-null  float64
 6   Merchant Location                  100000 non-null  object
 7   Card Present Status                100000 non-null  object
 8   Chip Usage                         100000 non-null  object
 9   Cross-border Transaction (Yes/No)  100000 non-null  object
 10  Acquiring Institution ID           100000 non-null  object
 11  Merchant Identifier                100000 non-null  object
 12  Merchant Category Code (MCC)       99997 non-null   float64
 13  Fraud Indicator (Yes/No)           100000 non-null  object
dtypes: datetime64[ns](1), float64(3), object(10)
memory usage: 10.7+ MB

In [10]:
df['Card Identifier']

0           card 1
1           card 2
2           card 3
3           card 4
4           card 5
           ...
99995    card 1213
99996    card 3761
99997     card 442
99998    card 1769
99999    card 6113
Name: Card Identifier, Length: 100000, dtype: object

In [12]:
df['Card Identifier'].value_counts()

Card Identifier
card 300     407
card 93      282
card 180     273
card 276     272
card 52      266
            ...
card 5819      1
card 5820      1
card 5823      1
card 3783      1
card 7872      1
Name: count, Length: 7872, dtype: int64

In [7]:
df['Cross-border Transaction (Yes/No)'].value_counts()

Cross-border Transaction (Yes/No)
No     85037
Yes    14845
0        118
Name: count, dtype: int64

In [36]:
df['Card Identifier'] = df['Card Identifier'].str.replace('card ', '').astype(int)

In [39]:
df.head()

,Card Identifier,Transaction Date,Transaction Time,Risk Assessment,Payment Method,Transaction Value,Merchant Location,Card Present Status,Chip Usage,Cross-border Transaction (Yes/No),Acquiring Institution ID,Merchant Identifier,Merchant Category Code (MCC),Fraud Indicator (Yes/No)
0,1,2023-05-11,1900-01-01 16:22:14,362.0,Paypass - Contactless,13.98,USA,CP,Yes,No,acquirer 1,merchant 1,5812.0,No
1,2,2023-06-05,1900-01-01 15:16:35,602.0,Online,24.64,USA,CNP,No,No,acquirer 2,merchant 2,4121.0,No
2,3,2023-06-05,1900-01-01 11:57:40,482.0,Unknown,15.00,USA,CNP,No,No,acquirer 3,merchant 3,7211.0,No
3,4,2023-07-20,1900-01-01 18:26:30,947.0,Online,30.56,USA,CNP,No,No,acquirer 1,merchant 4,5814.0,No
4,5,2023-03-03,1900-01-01 19:03:11,1382.0,Magnetic Stripe,50.85,USA,CP,No,No,acquirer 4,merchant 1,5812.0,No

In [15]:
df['card_id'].value_counts()

card_id
300     407
93      282
180     273
276     272
52      266
       ...
5819      1
5820      1
5823      1
3783      1
7872      1
Name: count, Length: 7872, dtype: int64

In [38]:
df['Transaction Time'] = pd.to_datetime(df['Transaction Time'], format='%H:%M:%S.%f', errors='coerce')

In [27]:
# Count the number of values that couldn't be converted
count_invalid = df['transaction_time'].isna().sum()

print("Number of values in unexpected format:", count_invalid)

Number of values in unexpected format: 22462

In [28]:
df_fraud = df[df['Fraud Indicator (Yes/No)'] == 'Yes']
df_fraud['transaction_time'].isna().sum()

80

In [19]:
df['Merchant Location'].value_counts()

Merchant Location
USA    85155
GBR     3573
FRA     1425
ESP     1018
NLD      775
       ...
BHR        1
GLP        1
GUY        1
BIH        1
BLR        1
Name: count, Length: 137, dtype: int64

In [32]:
df['Risk Assessment'].value_counts()

Risk Assessment
277.0     693
262.0     685
267.0     681
302.0     678
257.0     676
         ...
4222.0      1
4477.0      1
4917.0      1
4847.0      1
4867.0      1
Name: count, Length: 951, dtype: int64

In [33]:
df.columns

Index(['Card Identifier', 'Transaction Date', 'Transaction Time',
       'Risk Assessment', 'Payment Method', 'Transaction Value',
       'Merchant Location', 'Card Present Status', 'Chip Usage',
       'Cross-border Transaction (Yes/No)', 'Acquiring Institution ID',
       'Merchant Identifier', 'Merchant Category Code (MCC)',
       'Fraud Indicator (Yes/No)', 'card_id', 'transaction_time'],
      dtype='object')